### ISSUE TITLE
Formatter not registered for proto3 selector

### ISSUE THREAD

**Issue by d-enk** [bufbuild/vscode-buf#161]
You can't configure buf for proto3

```json
"[proto3]": {
  "editor.defaultFormatter": "bufbuild.vscode-buf"
},
```

`Extension 'Buf' is configured as formatter but it cannot format 'Protocol-Buffers'-files`

So if you have any other enabled extension for proto3 (like zxh404.vscode-proto3),
buf will not format.

**Comment by stefanvanburen** [comment]
Hi @d-enk, thanks for the issue. I'm able to reproduce, will take a look at your PR!
