### ISSUE TITLE
Cant get linter to work

### ISSUE THREAD

**Issue by thesiti92** [bufbuild/vscode-buf#172]
I've been trying to get the buf linter to work on my vscode. I have been using vscode-proto3 and even tried disabling it. When i do i think buf gives me some linter errors (theyre labeled as `[COMPILE]` in the tooltips ) but those are breaking syntax errors not linter hints. When i run `buf lint` in my workspace root it works as expected and outputs variable naming hints, etc... 

Was there anything in the setup that i missed? Do i need to add some action to my actionsOnSave config?

**Comment by xiaozhoz** [comment]
same here, how did you solve it?
