### ISSUE TITLE
vscode extension can not parse the latest buf binary version

### ISSUE THREAD

**Issue by scbizu** [bufbuild/vscode-buf#20]
## Reproduce 

* Install the latest buf binary (v1.0.0-rc1)
* Install the buf-vscode extension 
* buf-vscode throws a error: `Failed to get buf version: failed to parse version output: 1.0.0-rc1`

## Possible Fix

Why not use the standard semver regexp rules suggested by [semver](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) ?

Addressed here: https://regex101.com/r/vkijKf/1/

**Comment by timostamm** [comment]
I can reproduce, we'll get this fixed soon.

**Comment by timostamm** [comment]
We have just released a fix in v0.3.1.
