### ISSUE TITLE
Extension 'Buf' is configured as formatter but it cannot format 'Protocol Buffers'-files

### ISSUE THREAD

**Issue by hasit** [bufbuild/vscode-buf#256]
I am getting the following error in VSCode when I configure `vscode-buf` to be the default formatter for `.proto` files.

```
Formatting Extension 'Buf' is configured as formatter but it cannot format 'Protocol Buffers'-files
```

`buf` can be found in $PATH. 
``` 
$ which buf
/opt/homebrew/bin/buf
$ echo $PATH
... /opt/homebrew/bin /usr/local/bin ...
```

Here's the `proto3` section in my `settings.json` for reference:
```
  "[proto3]": {
    "editor.defaultFormatter": "bufbuild.vscode-buf",
    "editor.formatOnSave": true
  },
```

**Comment by neekolas** [comment]
I'm running into the same issue

**Comment by timostamm** [comment]
With VSCode v1.81.1, and the extension in v0.5.1, it seems to work as expected for me: The "Format Document" command formats, and save formats as well.

It is possible that another extension for proto files causes a conflict? The [Protobuf support](https://marketplace.visualstudio.com/items?itemName=peterj.proto) extension works well in combination with ours, adding syntax highlighting, but not causing conflicts that I'm aware of.

**Comment by hasit** [comment]
Thanks for verifying. I do not see the error now.
