### ISSUE TITLE
Add settings option to disable format on save

### ISSUE THREAD

**Issue by rinarakaki** [bufbuild/vscode-buf#331]
Since we cannot configure the formatting of buf, we want an option to disable the format on save behaviour of the buf VSCode extension at least. I hope you consider it. Thank you.

**Comment by nicksnyder** [comment]
Hi @rinarakaki , you can disable the format on save behavior by adding this to your user settings or workspace settings file:

```
    "[proto]": {
        "editor.formatOnSave": false
    },
```
