### ISSUE TITLE
Add a configuration hiding the lint's warning

### ISSUE THREAD

**Issue by FishGoddess** [bufbuild/vscode-buf#340]
Hi, I am using this plugin and it's good, so let me thank to all contributors~

However, some protos in my projects are not always 'standard' to protobuf (company has its own standard), like:
![image](https://github.com/bufbuild/vscode-buf/assets/36259784/ad53cafa-e793-43a6-b12a-78ad1a41fbb8)

The warning with the yellow line is so attractive, and I just want it to be not so attractive or hidden.
So maybe give us a chance to configure warning or lint?

Thank you for your reading : )

**Comment by srikrsna-buf** [comment]
Hey! You can adjust the lint options using a `buf.yaml` file. You can also ignore certain rules for specific files. Here's a overview of linting using `buf`: https://buf.build/docs/lint/overview#defaults-and-configuration

**Comment by FishGoddess** [comment]
> Hey! You can adjust the lint options using a `buf.yaml` file. You can also ignore certain rules for specific files. Here's a overview of linting using `buf`: https://buf.build/docs/lint/overview#defaults-and-configuration

It works! Thanks~
