### ISSUE TITLE
[Request] please add vscode-buf extension to `Open VSX Registry`

### ISSUE THREAD

**Issue by prosenjitjoy** [bufbuild/vscode-buf#346]
Currently, one way to install Buf extension to 'Code - OSS' is by compiling/packaging the source -> get vsix file -> installing via extension view's 'Install from VSIX...' as vscode-buf is not available in open-vsx.org yet.

I humbly request you to take necessary steps to make vscode-buf available in Open VSX Registry. As far as I understand, this will make Buf extension to appear in both code-oss and vscodium's extension browser by default without any tweaking in the settings. So users can have seamless experience who are using those flavor by choice or limited by some factors.

**Comment by UnstoppableMango** [comment]
Is this the same request as https://github.com/bufbuild/vscode-buf/issues/25?

**Comment by prosenjitjoy** [comment]
> Is this the same request as #25?

Sorry. Duplicate of #25

**Comment by prosenjitjoy** [comment]
Duplicate of #25

**Comment by prosenjitjoy** [comment]
> Is this the same request as #25?

Sorry. Duplicate of #25
